[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  NODE_VERSION = "20"
  HUGO_VERSION = "0.119.0"
  HUGO_ENABLEGITINFO = "true"

[build]
  command = "yarn build:webpack && hugo --gc --minify -s site -d ../dist"
  publish = "dist"

# Enable Git Gateway for DecapCMS
[build.processing]
  skip_processing = false

# Performance and Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers - optimized for mobile
    Cache-Control = "public, max-age=1800"
    
    # Preload critical resources

# Static assets caching - mobile optimized
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/logo.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"
    
# WebP images for better mobile performance
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/webp"
    
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.ttf"
  [headers.values]
    Content-Type = "font/ttf"
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000, immutable"

# Admin area security
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[context.deploy-preview]
  command = "yarn build:webpack && hugo --gc --minify -s site -d ../dist -D -F"

# Deploy preview headers - prevent indexing of preview URLs
[context.deploy-preview.headers]
  for = "/*"
  [context.deploy-preview.headers.values]
    X-Robots-Tag = "noindex, nofollow"

[dev]
  framework = "hugo"
  targetPort = 3000

# Asset redirects to fix 404s
[[redirects]]
  from = "/css/*"
  to = "/:splat"
  status = 200
  
[[redirects]]
  from = "/js/*"
  to = "/:splat"
  status = 200

# Redirects for SEO
[[redirects]]
  from = "/catalog/catalog/*"
  to = "/catalog/:splat"
  status = 301
  
[[redirects]]
  from = "/guides/guides/*"
  to = "/guides/:splat"
  status = 301

# [[plugins]]
#   package = "netlify-plugin-cypress"
# 
#   [plugins.inputs]
#     record = true