[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  NODE_VERSION = "20"
  HUGO_VERSION = "0.119.0"

[build]
  command = "yarn build"
  publish = "dist"

# Enable Git Gateway for DecapCMS
[build.processing]
  skip_processing = false

# Headers for proper CMS functionality
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[context.deploy-preview]
  command = "yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true