baseurl = "https://karma-fe.netlify.app/"
languageCode = "uk-UA"
title = "Karma - Електронні компоненти для дронів"

defaultContentLanguage = "uk"
defaultContentLanguageInSubdir = false


[languages]
  [languages.uk]
    title = "Karma - Електронні компоненти для дронів"
    languageName = "Українська"
    languageCode = "uk-UA"
    weight = 1
    # Эта настройка уберет `/uk/` из URL для украинской версии (по вашему желанию)
    # Параметры для украинской версии
    [languages.uk.params]
      description = "Karma - провідний постачальник електронних компонентів для дронів в Україні. ESC, відеопередавачі, політні стеки та інші компоненти."
      keywords = "дрони, ESC, відеопередавачі, політні стеки, електронні компоненти, FPV, безпілотники, Україна"

  [languages.en]
    title = "Karma - Electronic Components for Drones"
    languageName = "English"
    languageCode = "en-US"
    weight = 2
    # Параметры для английской версии
    [languages.en.params]
      description = "Karma - a leading supplier of electronic components for drones in Ukraine. ESCs, video transmitters, flight stacks and other components."
      keywords = "drones, ESC, video transmitters, flight stacks, electronic components, FPV, UAVs, Ukraine"


# Enable RSS for better SEO
enableRobotsTXT = true
enableGitInfo = true

# SEO and performance optimizations
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  
[minify.tdewolff.html]
  keepDocumentTags = true
  keepEndTags = true
  keepDefaultAttrVals = true
  keepWhitespace = false

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  catalog = "/catalog/:slug/"
  guides = "/guides/:slug/"
  blog = "/blog/:slug/"

# Sitemap configuration
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Security functions
[security.funcs]
  getenv = ['^HUGO_', '^CI$', '^CONTEXT$', '^NETLIFY']

[params]
  author = "Karma"
  images = ["img/og-image.jpg"]
  ogImage = "img/og-image.jpg"
  themeColor = "#1f2937"
  favicon = "img/favicon.ico"
  appleTouchIcon = "img/apple-touch-icon.png"

[build]
  writeStats = true

[imaging]
  resampleFilter = "lanczos"
  quality = 85
  anchor = "smart"
  
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4